// lib/objectbox/objectbox_store.dart
//
// Singleton wrapper around the ObjectBox Store.
// Must be initialized once before use:
//   await ObjectBoxStore.initialize();
//
// After initialization, access boxes via ObjectBoxStore.instance.settingsBox
// and ObjectBoxStore.instance.tokenBox.
//
// NOTE: objectbox.g.dart is generated by running:
//   flutter pub run build_runner build --delete-conflicting-outputs

import 'package:objectbox/objectbox.dart';
import 'models/app_settings.dart';
import 'models/auth_token.dart';
import '../objectbox.g.dart'; // generated by build_runner

class ObjectBoxStore {
  final Store _store;
  final Box<AppSettingsEntity> settingsBox;
  final Box<AuthTokenEntity> tokenBox;

  ObjectBoxStore._(this._store)
      : settingsBox = Box<AppSettingsEntity>(_store),
        tokenBox = Box<AuthTokenEntity>(_store);

  static ObjectBoxStore? _instance;

  /// Initialize the ObjectBox store. Safe to call multiple times.
  static Future<void> initialize() async {
    if (_instance != null) return;
    final store = await openStore();
    _instance = ObjectBoxStore._(store);
  }

  /// Access the singleton. Throws if [initialize] was not called first.
  static ObjectBoxStore get instance {
    assert(_instance != null,
        'ObjectBoxStore.initialize() must be called before use.');
    return _instance!;
  }

  void close() => _store.close();
}
