// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/scan_result.dart';
import 'services/pending_upload_service.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 721725170867704439),
      name: 'PendingUpload',
      lastPropertyId: const obx_int.IdUid(5, 7250243127728938201),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8994364513241901229),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 984946046464261326),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1335381626003117748),
            name: 'cropName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5615187422932218360),
            name: 'heatmap',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7250243127728938201),
            name: 'timestamp',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4370644069687472722),
      name: 'ScanResult',
      lastPropertyId: const obx_int.IdUid(13, 7294975111411018330),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4239879977828614092),
            name: 'obxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7322721130038158931),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 7849470855727856713)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 747324682361599860),
            name: 'cropName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7218036355069126426),
            name: 'diseaseName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8003564710369401172),
            name: 'confidence',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2038113888401866556),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8902727546959829966),
            name: 'hasDisease',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1523378393539782675),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3641155284511460434),
            name: 'severity',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1794122975604972449),
            name: 'fullLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6014305378228653753),
            name: 'qualityWarnings',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7786016877464585155),
            name: 'heatmapPng',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 7294975111411018330),
            name: 'rating',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 4370644069687472722),
      lastIndexId: const obx_int.IdUid(1, 7849470855727856713),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    PendingUpload: obx_int.EntityDefinition<PendingUpload>(
        model: _entities[0],
        toOneRelations: (PendingUpload object) => [],
        toManyRelations: (PendingUpload object) => {},
        getId: (PendingUpload object) => object.id,
        setId: (PendingUpload object, int id) {
          object.id = id;
        },
        objectToFB: (PendingUpload object, fb.Builder fbb) {
          final imagePathOffset = fbb.writeString(object.imagePath);
          final cropNameOffset = fbb.writeString(object.cropName);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, imagePathOffset);
          fbb.addOffset(2, cropNameOffset);
          fbb.addBool(3, object.heatmap);
          fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final cropNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final heatmapParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final timestampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final object = PendingUpload(
              id: idParam,
              imagePath: imagePathParam,
              cropName: cropNameParam,
              heatmap: heatmapParam,
              timestamp: timestampParam);

          return object;
        }),
    ScanResult: obx_int.EntityDefinition<ScanResult>(
        model: _entities[1],
        toOneRelations: (ScanResult object) => [],
        toManyRelations: (ScanResult object) => {},
        getId: (ScanResult object) => object.obxId,
        setId: (ScanResult object, int id) {
          object.obxId = id;
        },
        objectToFB: (ScanResult object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final cropNameOffset = fbb.writeString(object.cropName);
          final diseaseNameOffset = fbb.writeString(object.diseaseName);
          final imagePathOffset = fbb.writeString(object.imagePath);
          final severityOffset = object.severity == null
              ? null
              : fbb.writeString(object.severity!);
          final fullLabelOffset = object.fullLabel == null
              ? null
              : fbb.writeString(object.fullLabel!);
          final qualityWarningsOffset = object.qualityWarnings == null
              ? null
              : fbb.writeString(object.qualityWarnings!);
          final heatmapPngOffset = object.heatmapPng == null
              ? null
              : fbb.writeString(object.heatmapPng!);
          fbb.startTable(14);
          fbb.addInt64(0, object.obxId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, cropNameOffset);
          fbb.addOffset(3, diseaseNameOffset);
          fbb.addFloat64(4, object.confidence);
          fbb.addOffset(5, imagePathOffset);
          fbb.addBool(6, object.hasDisease);
          fbb.addInt64(7, object.date.millisecondsSinceEpoch);
          fbb.addOffset(8, severityOffset);
          fbb.addOffset(9, fullLabelOffset);
          fbb.addOffset(10, qualityWarningsOffset);
          fbb.addOffset(11, heatmapPngOffset);
          fbb.addInt64(12, object.rating);
          fbb.finish(fbb.endTable());
          return object.obxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final obxIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final cropNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final diseaseNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final confidenceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final hasDiseaseParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final ratingParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final severityParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final fullLabelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final qualityWarningsParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final heatmapPngParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final object = ScanResult(
              obxId: obxIdParam,
              id: idParam,
              cropName: cropNameParam,
              diseaseName: diseaseNameParam,
              confidence: confidenceParam,
              imagePath: imagePathParam,
              hasDisease: hasDiseaseParam,
              date: dateParam,
              rating: ratingParam,
              severity: severityParam,
              fullLabel: fullLabelParam,
              qualityWarnings: qualityWarningsParam,
              heatmapPng: heatmapPngParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PendingUpload] entity fields to define ObjectBox queries.
class PendingUpload_ {
  /// see [PendingUpload.id]
  static final id =
      obx.QueryIntegerProperty<PendingUpload>(_entities[0].properties[0]);

  /// see [PendingUpload.imagePath]
  static final imagePath =
      obx.QueryStringProperty<PendingUpload>(_entities[0].properties[1]);

  /// see [PendingUpload.cropName]
  static final cropName =
      obx.QueryStringProperty<PendingUpload>(_entities[0].properties[2]);

  /// see [PendingUpload.heatmap]
  static final heatmap =
      obx.QueryBooleanProperty<PendingUpload>(_entities[0].properties[3]);

  /// see [PendingUpload.timestamp]
  static final timestamp =
      obx.QueryDateProperty<PendingUpload>(_entities[0].properties[4]);
}

/// [ScanResult] entity fields to define ObjectBox queries.
class ScanResult_ {
  /// see [ScanResult.obxId]
  static final obxId =
      obx.QueryIntegerProperty<ScanResult>(_entities[1].properties[0]);

  /// see [ScanResult.id]
  static final id =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[1]);

  /// see [ScanResult.cropName]
  static final cropName =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[2]);

  /// see [ScanResult.diseaseName]
  static final diseaseName =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[3]);

  /// see [ScanResult.confidence]
  static final confidence =
      obx.QueryDoubleProperty<ScanResult>(_entities[1].properties[4]);

  /// see [ScanResult.imagePath]
  static final imagePath =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[5]);

  /// see [ScanResult.hasDisease]
  static final hasDisease =
      obx.QueryBooleanProperty<ScanResult>(_entities[1].properties[6]);

  /// see [ScanResult.date]
  static final date =
      obx.QueryDateProperty<ScanResult>(_entities[1].properties[7]);

  /// see [ScanResult.severity]
  static final severity =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[8]);

  /// see [ScanResult.fullLabel]
  static final fullLabel =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[9]);

  /// see [ScanResult.qualityWarnings]
  static final qualityWarnings =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[10]);

  /// see [ScanResult.heatmapPng]
  static final heatmapPng =
      obx.QueryStringProperty<ScanResult>(_entities[1].properties[11]);

  /// see [ScanResult.rating]
  static final rating =
      obx.QueryIntegerProperty<ScanResult>(_entities[1].properties[12]);
}
