// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox/models/app_settings.dart';
import 'objectbox/models/auth_token.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9125628107761496322),
    name: 'AppSettingsEntity',
    lastPropertyId: const obx_int.IdUid(4, 6188079036315868560),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8600839658447478941),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4249075913436322404),
        name: 'appLanguage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 635590196053385434),
        name: 'hasSelectedLanguage',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6188079036315868560),
        name: 'selectedCropsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2681194488126099012),
    name: 'AuthTokenEntity',
    lastPropertyId: const obx_int.IdUid(3, 6110391883866237725),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1870601136474160935),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3225288324155235555),
        name: 'token',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6110391883866237725),
        name: 'userDataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 2681194488126099012),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettingsEntity: obx_int.EntityDefinition<AppSettingsEntity>(
      model: _entities[0],
      toOneRelations: (AppSettingsEntity object) => [],
      toManyRelations: (AppSettingsEntity object) => {},
      getId: (AppSettingsEntity object) => object.id,
      setId: (AppSettingsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettingsEntity object, fb.Builder fbb) {
        final appLanguageOffset = fbb.writeString(object.appLanguage);
        final selectedCropsJsonOffset = fbb.writeString(
          object.selectedCropsJson,
        );
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, appLanguageOffset);
        fbb.addBool(2, object.hasSelectedLanguage);
        fbb.addOffset(3, selectedCropsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AppSettingsEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..appLanguage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..hasSelectedLanguage = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            8,
            false,
          )
          ..selectedCropsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');

        return object;
      },
    ),
    AuthTokenEntity: obx_int.EntityDefinition<AuthTokenEntity>(
      model: _entities[1],
      toOneRelations: (AuthTokenEntity object) => [],
      toManyRelations: (AuthTokenEntity object) => {},
      getId: (AuthTokenEntity object) => object.id,
      setId: (AuthTokenEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AuthTokenEntity object, fb.Builder fbb) {
        final tokenOffset = fbb.writeString(object.token);
        final userDataJsonOffset = fbb.writeString(object.userDataJson);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tokenOffset);
        fbb.addOffset(2, userDataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AuthTokenEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..token = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..userDataJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettingsEntity] entity fields to define ObjectBox queries.
class AppSettingsEntity_ {
  /// See [AppSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[0].properties[0],
  );

  /// See [AppSettingsEntity.appLanguage].
  static final appLanguage = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[1],
  );

  /// See [AppSettingsEntity.hasSelectedLanguage].
  static final hasSelectedLanguage =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[0].properties[2]);

  /// See [AppSettingsEntity.selectedCropsJson].
  static final selectedCropsJson = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[0].properties[3],
  );
}

/// [AuthTokenEntity] entity fields to define ObjectBox queries.
class AuthTokenEntity_ {
  /// See [AuthTokenEntity.id].
  static final id = obx.QueryIntegerProperty<AuthTokenEntity>(
    _entities[1].properties[0],
  );

  /// See [AuthTokenEntity.token].
  static final token = obx.QueryStringProperty<AuthTokenEntity>(
    _entities[1].properties[1],
  );

  /// See [AuthTokenEntity.userDataJson].
  static final userDataJson = obx.QueryStringProperty<AuthTokenEntity>(
    _entities[1].properties[2],
  );
}
